// Autocomplete suggestions used by StartShiftModal and the calendar's
// day-detail drawer. Users can still type custom names.
export const KNOWN_HOLIDAYS: readonly string[] = [
  "New Year's Day",
  "Valentine's Day",
  "Chinese New Year",
  "Holy Week",
  "Maundy Thursday",
  "Good Friday",
  "Black Saturday",
  "Easter Sunday",
  "Araw ng Kagitingan",
  "Labor Day",
  "Mother's Day",
  "Independence Day",
  "Father's Day",
  "Eid'l Fitr",
  "Eid'l Adha",
  "Ninoy Aquino Day",
  "National Heroes Day",
  "Bonifacio Day",
  "Halloween",
  "All Saints' Day",
  "All Souls' Day",
  "Christmas Eve",
  "Christmas Day",
  "Rizal Day",
  "New Year's Eve",
];
